//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarPrototype
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public string Organization { get; set; }
        public string Requestor { get; set; }
        public string ThemeColor { get; set; }
        public bool IsFullDay { get; set; }
        public string Organization_Division { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string requestorDepartment { get; set; }
        public string requestorPhone { get; set; }
        public string Purpose { get; set; }
    }
}
